int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int helper(int n, int i);
int helper_prime(int n, int i, int limit);
int is_palindrome(char *s);
int _strlen_recursion(char *s);
int pal_check(char *a, int length);
int wildcmp(char *s1, char *s2);
